### ISSUE TITLE
float attributes raise a TypeError

### ISSUE THREAD

**Issue by fm94** [tanjascats/fingerprinting-toolbox#15] opened 2021-04-30 11:38 UTC
When trying the universal scheme insertion (`fingerprinted_data_weighted = scheme.insertion(main_X, secret_key=secret_key, recipient_id=recipient_id, attributes_weights=rf_model.feature_importances_)`) I get the following error:
```
Traceback (most recent call last):
  File "run.py", line 240, in <module>
    main()
  File "run.py", line 181, in main
    fingerprinted_data_weighted = scheme.insertion(main_X, secret_key=secret_key, recipient_id=recipient_id, attributes_weights=rf_model.feature_importances_)
  File "~/fingerprinting-toolbox/scheme/_universal.py", line 158, in insertion
    marked_attribute = set_bit(attribute_val, bit_idx, mark_bit)
  File "~/fingerprinting-toolbox/utils.py", line 87, in set_bit
    val = val & mask
TypeError: unsupported operand type(s) for &: 'numpy.float64' and 'int'
```

To reproduce the error use the Bank_Personal_Loan_Modelling.csv dataset (https://www.kaggle.com/krantiswalke/bank-personal-loan-modelling-supervised-learning). The problem happens exactly with the 'CCAvg' attribute (type float) and is resolved if the latter is excluded.

**Comment by tanjascats** [comment] 2021-05-03 22:14
Hi!

Thanks for reporting! However, I cannot reproduce the error with the given dataset. 

The support for decimal data should have been fixed with some of the recent commits. Can you confirm that this error emerged with the current code from the master branch (commits after March 15)?

**Closed** 2022-02-02 16:02 UTC
